version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet-dev
    working_dir: /app
    command: sleep infinity
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5289:5289"
